In [6]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
vector = [1,3,4,6,7]

In [3]:
type(vector)

list

In [4]:
vector = np.array([1,3,4,6,7])

In [5]:
type(vector)

numpy.ndarray

In [6]:
matrix = np.array([[1,2,3], [3,4,6], [7,8,9]])

In [7]:
print(matrix)

[[1 2 3]
 [3 4 6]
 [7 8 9]]


In [8]:
# to get the shape of the array .shape
matrix.shape

(3, 3)

In [9]:
grid_value = np.array([[2,4,6], [8,20,40]])

In [10]:
print(grid_value)

[[ 2  4  6]
 [ 8 20 40]]


In [11]:
grid_value.shape

(2, 3)

In [12]:
## functions like ones and zeroes
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Accessing Numpy Array
* np.array[vertical index, horinzontal index] - for one element
* np.array[vertical start:vertical and, horizontal start:horizontal end] - for more than one element

In [22]:
values = [[1,2,3], [4,5,6]]
values_grid = np.array(values)


In [23]:
print(values_grid)

[[1 2 3]
 [4 5 6]]


In [25]:
#  Top left element
values_grid[0,0]

1

In [26]:
# first row
values_grid[0,:]

array([1, 2, 3])

In [28]:
# first column
values_grid[:,0]

array([1, 4])

In [32]:
# first two  rows and first two columns
values_grid[0:2, 0:2]

array([[1, 2],
       [4, 5]])

# 

In [14]:
print(grid_value)

[[ 2  4  6]
 [ 8 20 40]]


In [15]:
grid_value[0,1]

4

In [16]:
grid_value[0,:]

array([2, 4, 6])

In [17]:
grid_value[:,1]

array([ 4, 20])

In [18]:
grid_value[:,1]

array([ 4, 20])

In [19]:
grid_value[0:2, 0:2]

array([[ 2,  4],
       [ 8, 20]])

### Bolean array Indexing

In [28]:
# select all values greater than 2
print(grid_value)

[[ 2  4  6]
 [ 8 20 40]]


In [33]:
print(grid_value > 2)
grid_value[grid_value > 2]

[[False  True  True]
 [ True  True  True]]


array([ 4,  6,  8, 20, 40])

In [34]:
grid_value[grid_value < 6]

array([2, 4])

In [35]:
grid_value[(grid_value < 3) | (grid_value > 5)]

array([ 2,  6,  8, 20, 40])

# Modifying Numpy Arrays

In [38]:
# adding elements to an array
import numpy as np
grid_value = np.array([[2,4,6], [8,20,40]])

In [39]:
print(grid_value)

[[ 2  4  6]
 [ 8 20 40]]


In [41]:
# example of adding a row
grid_value_extra =  np.append(grid_value, [[92, 88, 70]], axis=0)
grid_value_extra

array([[ 2,  4,  6],
       [ 8, 20, 40],
       [92, 88, 70]])

In [42]:
# example adding a column
np_column = np.array([[74], [19], [40]])
grid_value_extra_extra = np.append(grid_value_extra, np_column, axis=1)

grid_value_extra_extra

array([[ 2,  4,  6, 74],
       [ 8, 20, 40, 19],
       [92, 88, 70, 40]])

In [51]:
# removing elements
grid_value_del_row = np.delete(grid_value, [1], axis=0)

print(grid_value_del_row)

print("_______")
grid_value


[[2 4 6]]
_______


array([[ 2,  4,  6],
       [ 8, 20, 40]])

###  Methods (arange, reshape, linspace, eye)

In [52]:
# arange - allows you to create a range of parameter for your arrays

arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
# Adding steps to your range
arr_step = np.arange(0,20, 2)
arr_step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# reshape

arr.shape

(20,)

In [54]:
arr_reshape = arr.reshape(4,5)
arr_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
arr_reshape = arr.reshape(5,4)
arr_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
# linspace

lin_space = np.linspace(0,20)
lin_space

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [57]:
# Spacing by 10
lin_spaces = np.linspace(0,20,10)
lin_spaces

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [58]:
# Spacing by 5
lin_spaces = np.linspace(0,20,5)
lin_spaces

array([ 0.,  5., 10., 15., 20.])

In [36]:
# Eye

id_matrix = np.eye(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Method and Function: sum, min, max,argmin,argmax

In [59]:
# sum function
print(grid_value)
grid_value.sum()

[[ 2  4  6]
 [ 8 20 40]]


80

In [60]:
# sum of each row

grid_value.sum(axis=0)

array([10, 24, 46])

In [62]:
# sum of each column

grid_value.sum(axis=1)

array([12, 68])

In [64]:
# min of each row
grid_value.min(axis=1)

array([2, 8])

In [66]:
# min of each column
grid_value.min(axis=0)

array([2, 4, 6])

In [67]:
# max of each row
grid_value.max(axis=1)

array([ 6, 40])

In [68]:
# argmin: index position of min
# min of each row
grid_value.argmin(axis=1)

array([0, 0], dtype=int64)

In [70]:
# argmax: index position of min
# min of each columns
grid_value.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [71]:
# argmax: index position of max
# max of each row
grid_value.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [72]:
# argmax: index position of max
# max of each column
grid_value.argmax(axis=1)

array([2, 2], dtype=int64)

### Random: rand, randn,ranint

In [76]:
# rand allows to create random values between 0-1
rand_arr = np.random.rand(3,3)
rand_arr

array([[0.41612553, 0.56849963, 0.72301005],
       [0.27987067, 0.568523  , 0.65332466],
       [0.32592472, 0.0503316 , 0.5493559 ]])

In [89]:
# randn: creates array from a standard normal distribution
randn_arr = np.random.randn(3,3)
randn_arr

array([[-1.30194312, -0.98144636,  0.0531732 ],
       [ 1.50419101, -1.44947532, -0.15430889],
       [ 0.7884223 , -0.07674343,  1.07258141]])

In [86]:
#randint: create random values between 1 - 100

randint_arr = np.random.randint(1,100, size=(4,3))
randint_arr

array([[49, 96, 85],
       [11, 31, 48],
       [32, 76, 31],
       [62, 53, 73]])

# Pandas

In [104]:
!pip install pandas

In [116]:
import pandas as pd
import numpy as np

In [112]:
# List
# Dictionaries
# Numpy arrays

# creating pandas series from List
age = [25,30,35,40]
age_series = pd.Series(age, name="Age")
print(age_series)

0    25
1    30
2    35
3    40
Name: Age, dtype: int64


In [114]:
# creating pandas series from Dictionary

data_dict = {"a": 100, "b": 200, "c": 400, "d": 400}

series_from_dict = pd.Series(data_dict)
print(series_from_dict)

a    100
b    200
c    400
d    400
dtype: int64


In [118]:
# creating pandas series from Numpy array
np_array = np.array([10,20,30,40,50])

series_from_array = pd.Series(np_array)

print(series_from_array)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [48]:
# Creating a dataframe from a List
data_columns = ["CustomerID", "Age", "Income"]
data = [[101,25,50000], [102,30,6000], [103,35,70000]]
customer_df = pd.DataFrame(data, columns=data_columns)

print(customer_df)

   CustomerID  Age  Income
0         101   25   50000
1         102   30    6000
2         103   35   70000


In [126]:
# Creating a dataframe from dictionary

dict_data = {'CustomerID': [101,102,103], 'Age': [25,30,35], 'Income': [50000, 60000, 70000]}
dict_df = pd.DataFrame(dict_data)

print(dict_df)

   CustomerID  Age  Income
0         101   25   50000
1         102   30   60000
2         103   35   70000


## Basic Operations in Pandas

In [130]:
# Selecting a column
customer_df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [144]:
# Selecting multiple columns
customer_df[['CustomerID','Age']]

CustomerID  Age
0         101   25
1         102   30
2         103   35

In [152]:
# adding a new column

customer_df['Savings'] = customer_df['Income'] * 0.1
customer_df

CustomerID  Age  Income  Savings
0         101   25   50000   5000.0
1         102   30    6000    600.0
2         103   35   70000   7000.0

In [10]:
import pandas as pd
from datetime import datetime

#sample data for my dataframe

data = {
    'CustomerID': [101, 102, 103, 104, 105],
    'CustomerName': ['John Smith', 'Alice Johnson', 'Bob Smith', 'Eve Black', 'Jane Doe'],
    'Age': [25,30,35,40,45],
    'Income': [50000,60000,70000,80000,90000],
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Amount': [1000, 1500, 2000, 2500, 3000],
    'Region': ['North', 'South', 'East', 'West', 'North-west'],
    'SaleDate': [datetime(2023,1,1), datetime(2023,1,2), datetime(2023,1,3), datetime(2023,1,4), datetime(2023,1,5)]
}

# Create Dataframe

sales_df = pd.DataFrame(data)
sales_df

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

    SaleDate  
0 2023-01-01  
1 2023-01-02  
2 2023-01-03  
3 2023-01-04  
4 2023-01-05

In [12]:
# writing dataframe to csv

sales_df.to_csv('Bank_sales.csv', index=False)

In [114]:
# Reading a csv file into dataframe

sales = pd.read_csv(r'C:\Users\User\Bank_sales.csv')
sales

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

     SaleDate  
0  2023-01-01  
1  2023-01-02  
2  2023-01-03  
3  2023-01-04  
4  2023-01-05

In [201]:
# projecting and filter

income_df = sales_df[['Income', 'Age']]
income_df

Income  Age
0   50000   25
1   60000   30
2   70000   35
3   80000   40
4   90000   45

In [207]:
high_income = sales_df[sales_df['Income'] > 70000]
high_income

CustomerID CustomerName  Age  Income Product  Amount      Region   SaleDate
3         104    Eve Black   40   80000       D    2500        West 2023-01-04
4         105     Jane Doe   45   90000       E    3000  North-west 2023-01-05

### Perfoming total aggregation

In [213]:
# sum
total_income = sales_df['Income'].sum()

total_income

350000

In [215]:
#  mean
average_age = sales_df['Age'].mean()
average_age

35.0

### Joins - Merges

In [14]:
sales_df

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

    SaleDate  
0 2023-01-01  
1 2023-01-02  
2 2023-01-03  
3 2023-01-04  
4 2023-01-05

In [24]:
Product_df = pd.DataFrame({
    'Product': ['A', 'B', 'C'], 
    'Category': ['Finance', 'Investment', 'Insurance'],
    })
Product_df

Product    Category
0       A     Finance
1       B  Investment
2       C   Insurance

In [28]:
# INner join
joined_df = pd.merge(sales_df, Product_df, on='Product', how='inner')
joined_df

CustomerID   CustomerName  Age  Income Product  Amount Region   SaleDate  \
0         101     John Smith   25   50000       A    1000  North 2023-01-01   
1         102  Alice Johnson   30   60000       B    1500  South 2023-01-02   
2         103      Bob Smith   35   70000       C    2000   East 2023-01-03   

     Category  
0     Finance  
1  Investment  
2   Insurance

In [30]:
Joined_df = sales_df.merge(Product_df, on='Product', how='inner')
joined_df

CustomerID   CustomerName  Age  Income Product  Amount Region   SaleDate  \
0         101     John Smith   25   50000       A    1000  North 2023-01-01   
1         102  Alice Johnson   30   60000       B    1500  South 2023-01-02   
2         103      Bob Smith   35   70000       C    2000   East 2023-01-03   

     Category  
0     Finance  
1  Investment  
2   Insurance

In [94]:
# left join

left_join_df = pd.merge(sales_df, Product_df, on='Product', how='left')
left_join_df

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

    SaleDate    Category  
0 2023-01-01     Finance  
1 2023-01-02  Investment  
2 2023-01-03   Insurance  
3 2023-01-04         NaN  
4 2023-01-05         NaN

In [75]:
# right Join
right_join_df = pd.merge(sales_df, customer_df, on='CustomerID', how='right')
right_join_df

CustomerID   CustomerName  Age_x  Income_x Product  Amount Region  \
0         101     John Smith     25     50000       A    1000  North   
1         102  Alice Johnson     30     60000       B    1500  South   
2         103      Bob Smith     35     70000       C    2000   East   

    SaleDate  Age_y  Income_y  
0 2023-01-01     25     50000  
1 2023-01-02     30      6000  
2 2023-01-03     35     70000

## Advanced Pandas

In [57]:
# Reading an excel file
excel_df = pd.read_excel(r'C:\Users\User\Downloads\Apocolypse Food Prep - Bins Lists Tutorial.xlsx')
excel_df

Product ID               Product Name  Price  Production Cost
0       10001                 Nylon Rope  30.99            13.67
1       10002         Waterproof Matches   7.99             2.89
2       10003       Stainless Steel Axe   45.50            32.45
3       10004                   Backpack  39.99            26.92
4       10005  Multitool Survivial Knife  28.99            10.58
5       10006   Solar Battery Flashlight  26.49            13.41
6       10007        Weatherproof Jacket  79.99            30.59
7       10008                  Duct Tape   6.25             4.87
8       10009             Water Purifier  30.25            17.93
9       10010                   N95 Mask   2.75             1.01

In [80]:
# Handling Missing Values

left_join_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   CustomerID    5 non-null      int64         
 1   CustomerName  5 non-null      object        
 2   Age           5 non-null      int64         
 3   Income        5 non-null      int64         
 4   Product       5 non-null      object        
 5   Amount        5 non-null      int64         
 6   Region        5 non-null      object        
 7   SaleDate      5 non-null      datetime64[ns]
 8   Category      3 non-null      object        
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 492.0+ bytes


In [88]:
# Drop missing Values
left_join_df.dropna(inplace=True)
left_join_df

CustomerID   CustomerName  Age  Income Product  Amount Region   SaleDate  \
0         101     John Smith   25   50000       A    1000  North 2023-01-01   
1         102  Alice Johnson   30   60000       B    1500  South 2023-01-02   
2         103      Bob Smith   35   70000       C    2000   East 2023-01-03   

     Category  
0     Finance  
1  Investment  
2   Insurance

In [96]:
# filling missing values with appropriate values

left_join_df.fillna('unknown', inplace= True)
left_join_df

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

    SaleDate    Category  
0 2023-01-01     Finance  
1 2023-01-02  Investment  
2 2023-01-03   Insurance  
3 2023-01-04     unknown  
4 2023-01-05     unknown

In [98]:
# Data type conversion/ Data type standardization

left_join_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   CustomerID    5 non-null      int64         
 1   CustomerName  5 non-null      object        
 2   Age           5 non-null      int64         
 3   Income        5 non-null      int64         
 4   Product       5 non-null      object        
 5   Amount        5 non-null      int64         
 6   Region        5 non-null      object        
 7   SaleDate      5 non-null      datetime64[ns]
 8   Category      5 non-null      object        
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 492.0+ bytes


In [104]:
# converting datatype to str
left_join_df['CustomerID'] = left_join_df['CustomerID'].astype(str)
left_join_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   CustomerID    5 non-null      int32         
 1   CustomerName  5 non-null      object        
 2   Age           5 non-null      int64         
 3   Income        5 non-null      int64         
 4   Product       5 non-null      object        
 5   Amount        5 non-null      int64         
 6   Region        5 non-null      object        
 7   SaleDate      5 non-null      datetime64[ns]
 8   Category      5 non-null      object        
dtypes: datetime64[ns](1), int32(1), int64(3), object(4)
memory usage: 472.0+ bytes


In [106]:
# Grouping and aggregating data

sales_df

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

    SaleDate  
0 2023-01-01  
1 2023-01-02  
2 2023-01-03  
3 2023-01-04  
4 2023-01-05

In [108]:
grouped_df = sales_df.groupby('Product').agg({'Amount': ['sum', 'mean'], 'Age': 'mean'})
grouped_df

Amount           Age
           sum    mean  mean
Product                     
A         1000  1000.0  25.0
B         1500  1500.0  30.0
C         2000  2000.0  35.0
D         2500  2500.0  40.0
E         3000  3000.0  45.0

In [118]:
# handling duplicate values
tables =  [sales_df,  sales]
sales_dup = pd.concat(tables)
sales_dup

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

              SaleDate  
0  2023-01-01 00:00:00  
1  2023-01-02 00:00:00  
2  2023-01-03 00:00:00  
3  2023-01-04 00:00:00  
4  2023-01-05 00:00:00  
0           2023-01-01  
1           2023-01-02  
2           2023-01-03  
3           2023-01-04  
4           2023-01-05

In [124]:
sales_dup.drop_duplicates(subset='CustomerID', keep='first', inplace=True)

sales_dup

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

              SaleDate  
0  2023-01-01 00:00:00  
1  2023-01-02 00:00:00  
2  2023-01-03 00:00:00  
3  2023-01-04 00:00:00  
4  2023-01-05 00:00:00

In [126]:
#sorting data
sorted_df = sales_df.sort_values(by='Income', ascending=False)
sorted_df

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
4         105       Jane Doe   45   90000       E    3000  North-west   
3         104      Eve Black   40   80000       D    2500        West   
2         103      Bob Smith   35   70000       C    2000        East   
1         102  Alice Johnson   30   60000       B    1500       South   
0         101     John Smith   25   50000       A    1000       North   

    SaleDate  
4 2023-01-05  
3 2023-01-04  
2 2023-01-03  
1 2023-01-02  
0 2023-01-01

In [128]:
# Changing a column name
sales_df.rename(columns={'Income':'Salary'}, inplace=True)

sales_df

CustomerID   CustomerName  Age  Salary Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

    SaleDate  
0 2023-01-01  
1 2023-01-02  
2 2023-01-03  
3 2023-01-04  
4 2023-01-05

### Indexing and Slicing in Pandas

In [132]:
sales

CustomerID   CustomerName  Age  Income Product  Amount      Region  \
0         101     John Smith   25   50000       A    1000       North   
1         102  Alice Johnson   30   60000       B    1500       South   
2         103      Bob Smith   35   70000       C    2000        East   
3         104      Eve Black   40   80000       D    2500        West   
4         105       Jane Doe   45   90000       E    3000  North-west   

     SaleDate  
0  2023-01-01  
1  2023-01-02  
2  2023-01-03  
3  2023-01-04  
4  2023-01-05